### ISSUE TITLE
Possible roof day labeled as "No"

### ISSUE THREAD

**Issue by Zacharias3690** [nathanjohnson320/roofday#2]
## Steps to reproduce
Temperature: 86
UV Index: 1
wind speed: 3.6
precipitation: 0%
Metric: 3.98

## Current output
Roof time? No

## Expected output
Roof time? Yes

## Screenshot of issue
![screen shot 2017-05-16 at 3 10 43 pm](https://cloud.githubusercontent.com/assets/1680873/26123781/20219f20-3a4a-11e7-888b-80f83e4ce126.png)

**Comment by nathanjohnson320** [comment]
Not an issue

**Comment by Zacharias3690** [comment]
Optimal roof day weather should be reported as such.
